# Docker Compose for local development
version: '3.8'

services:
  app:
    build: .
    ports:
      - "8123:8123"
    environment:
      - ENVIRONMENT=development
      - API_KEY=dev_api_key_123
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - USE_GCS_STORAGE=false
    volumes:
      - .:/app
      - /app/__pycache__
    command: uvicorn fastapi_youtube_analyzer:app --host 0.0.0.0 --port 8123 --reload
    depends_on:
      - redis
    
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    
volumes:
  redis_data:
